# Server Configuration
server.servlet.context-path=/api

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/5emePi
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohamedamineezzaouia3@gmail.com
spring.mail.password=Nadia1234567..
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secret=9rzzG0DSZiUwjAGHPBX3NVrbijBV3Pz65/CIVwxrGbc=

# RapidAPI Configuration
rapid.api.key=e15eb8421cmsh4b9a6933420087cp1246ccjsnbc7f2f2e5179
twelvedata.api.host=twelve-data1.p.rapidapi.com

# AlphaVantage API Configuration
alphavantage.api.key=8LTW89B7OEV46XQF

# News API Configuration
news.api.key=4dfdb497c3e445358bf2a87bb75d2120

# Logging Configuration
logging.level.root=INFO
server.port=8084
logging.level.org.springframework.web=DEBUG

